# Generated by Django 4.1.1 on 2022-09-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_bookings_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='user',
            field=models.PositiveIntegerField(blank=True, default=4),
            preserve_default=False,
        ),
    ]
