# Generated by Django 4.0 on 2022-09-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_bookings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
