# Generated by Django 4.0 on 2022-09-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_bookings_checked_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='checked_in',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
